platform:
    - x86

environment:
    global:
        CYG_ROOT: C:/cygwin
        CYG_CACHE: C:/cygwin/var/cache/setup
        CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
        CC: gcc
    matrix:
        - CYG_ARCH: x86

install:
    - 'cinst 7zip.commandline'
    - 'appveyor DownloadFile http://cygwin.com/setup-%CYG_ARCH%.exe -FileName setup.exe'
    - 'setup.exe -qnNdO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P make -P gcc-core -P cmake >NUL'
    - '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER/libelf-0.8.13 && ./configure && make && make install'
    - 'appveyor DownloadFile https://nmap.org/npcap/dist/npcap-sdk-1.11.zip'
    - 'dir'
    - 'mkdir npcap-sdk'
    - '7za x .\npcap-sdk-1.11.zip -o./npcap-sdk'
    - 'xcopy .\npcap-sdk\Lib\wpcap.lib C:\cygwin\lib'
    - 'xcopy .\npcap-sdk\Lib\Packet.lib C:\cygwin\lib'
    - 'xcopy /Y /E .\npcap-sdk\Include\*.* C:\cygwin\usr\include\'

build_script:
    - '%CYG_ROOT%/bin/bash -lc "ls $APPVEYOR_BUILD_FOLDER'
    - '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER && mkdir -p build'
    - '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER/build && cmake ..'
    - '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER/build && make'
    - 'xcopy C:\cygwin\bin\cygwin1.dll .\build\stable'

artifacts:
  - path: 'build/stable/dynamips.exe'
  - path: 'build/stable/cygwin1.dll'
